config/routes.rb
Rails.application.routes.draw do
  get 'messages/create'
  devise_for :users
  root to: "pages#home"

  get "search", to: "universes#search"
  resources :universes, only: [:index, :show] do
    resources :bookmarks, only: [:create, :destroy]
  end

  resources :stories, only: [:show]

  resources :pages, only: [:show]

  resources :tags, only: [:show]

  resources :users, only: [:show] do
    resources :chatrooms, only: [:create]
    member do
      post :add_friend
      patch :accept_friendship
      delete :decline_friendship
      get :friends
      delete :delete_friendship
    end
  end

  resources :chatrooms, only: [:show] do
    resources :messages, only: [:create]
  end

  resources :avatars, only: %i[new create]
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :friendships_as_asker, class_name: "Friendship", foreign_key: :asker_id, dependent: :destroy
  has_many :friendships_as_receiver, class_name: "Friendship", foreign_key: :receiver_id, dependent: :destroy

  has_many :bookmarks, dependent: :destroy
  has_many :universes, dependent: :destroy
  has_many :chatrooms, dependent: :destroy
  has_many :messages, dependent: :destroy

end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :set_user, only: [:show, :add_friend]
  def show
    @user = User.find(params[:id])
    authorize @user
    @universes = Universe.includes(:user).all
    @pending_friendships = current_user.friendships_as_receiver.where(is_accepted: false)
    @chatroom = Chatroom.find_by("sender_id = ? OR recipient_id = ?", @user.id, @user.id)

  end

  def add_friend
    authorize @user
    if current_user != @user
      Friendship.create(asker_id: current_user.id, receiver_id: @user.id)
    end
    redirect_to user_path(@user)
  end

  def friends
    authorize current_user
    @user = User.find(params[:id])
    @friendships = Friendship.where("asker_id = ? OR receiver_id = ?", @user.id, @user.id).where(is_accepted: true)
    @chatroom = Chatroom.find_by("sender_id = ? OR recipient_id = ?", @user.id, @user.id)

  end

  def decline_friendship
    authorize current_user
    @friendship = Friendship.find(params[:id])
    @friendship.destroy!
    redirect_to current_user, allow_other_host: true
  end

  def delete_friendship
    authorize current_user
    @friendship = Friendship.find_by(id: params[:id], is_accepted: true)
    @friendship.destroy!
    redirect_to friends_user_path  ,allow_other_host: true
  end

  def accept_friendship
    authorize current_user
    @friendship = Friendship.find(params[:id])
    @friendship.update(is_accepted: true)
    @chatroom = Chatroom.new(sender_id: @friendship.asker_id, recipient_id:@friendship.receiver_id,
                             name:"#{@friendship.asker.nickname} & #{@friendship.receiver.nickname}")
    @chatroom.save!

    redirect_to current_user, allow_other_host: true
  end


  private

  def set_user
    @user = User.find(params[:id])
  end
end

app/views/users/friends.html.erb
<div class="container my-3">

  <% @friendships.each do |f|  %>

    <div class="row justify-content-center mb-2">

      <% if @user == f.asker %>

        <% right_chatroom = Chatroom.find_by(sender_id: f.asker_id, recipient_id: f.receiver_id) || Chatroom.find_by(sender_id: f.receiver_id, recipient_id: f.asker_id) %>
        <%=link_to(user_path(f.receiver)) do%>


          <div class="d-flex justify-content-between align-items-center friendship-card">
            <div class="avatar-svg"><%= f.receiver.avatar_img.html_safe %></div>

            <div class="user_friends">
              <%= f.receiver.nickname %>
            </div>

        <%end%>
            <% if @user == current_user %>
            <div class="two-buttons">

            <%= link_to chatroom_path(right_chatroom) do%>
                <i class="fas fa-comment"></i>
            <%end%>
            <%= link_to delete_friendship_user_path(f), data: {turbo_method: :delete, turbo_confirm: "Are you sure?"} do %>
                <i class="far fa-trash-alt"></i>
            <% end %>
            <% end %>

          </div>
        </div>

      <%elsif @user == f.receiver  %>

        <% right_chatroom = Chatroom.find_by(sender_id: f.asker_id, recipient_id: f.receiver_id) || Chatroom.find_by(sender_id: f.receiver_id, recipient_id: f.asker_id) %>
        <%=link_to(user_path(f.asker)) do %>

          <div class="d-flex justify-content-between align-items-center friendship-card text-center mt-2">

            <div class="avatar-svg"><%= f.asker.avatar_img.html_safe %></div>
            <div class="user_friends">
              <%= f.asker.nickname%>
            </div>

        <%end%>
            <% if @user == current_user%>

              <div class="two-buttons">
              <%= link_to chatroom_path(right_chatroom) do %>
                  <i class="fas fa-comment fa-xl"> </i>
              <%end%>

              <%= link_to delete_friendship_user_path(f), data: {turbo_method: :delete, turbo_confirm: "Are you sure?"} do %>
                  <i class="far fa-trash-alt fa-xl"> </i>
              <% end %>

            <% end %>
            </div>

          </div>

      <%end%>

    </div>

  <% end %>

</div>

app/views/users/show.html.erb
<div>

  <div class="container my-4 d-flex profile-user">

    <div>
      <%# <%= image_tag("https://res.cloudinary.com/djkudqafd/image/upload/dl_100/e_loop:0/Mayara_Turn_2_suniki.gif",height: 200, crop: :fill) %>

      <div class="avatar-svg-profile"><%= @user.avatar_img.html_safe %></div>

      <% if @user == current_user %>
        <div class="d-flex justify-content-center flex-wrap align-items-center">
          <%= link_to "edit avatar", new_avatar_path, class:"button-two-medium mt-3  p-0" %>
          <%= link_to "logout", destroy_user_session_path, data: {turbo_method: :delete} , class: "button-two-medium mt-2 p-0"%>
        </div>
      <% end %>

    </div>

    <div class="align-items-center ">

      <div class="profile-name-font">
        <p class="fw-bold fs-4 mb-1 pb-0 mt-4">I'm</p>
        <h1 class="fs-1 mt-0 pt-0"><%=@user.nickname%></h1>
      </div>

      <div>
        <p class="mt-5 bio-profile-font"><%=@user.bio%></p>
      </div>

    </div>

  </div>

  <div class="profile-container-card" >

    <%= link_to(friends_user_path(@user)) do %>
      <div class="profile-content">
        <h3>friends</h3>

        <p><% total_friendships = Friendship.where("asker_id = ? OR receiver_id = ?", @user.id, @user.id).where(is_accepted: true).count%></p>
        <p><%= total_friendships%>
      </div>
    <%end%>


    <div class="profile-content">
      <h3>favs</h3>
      <p><%= @user.bookmarks.count %></p>
    </div>

    <div class="profile-content">
      <h3>reads</h3>
      <p>1</p>
    </div>

  </div>



  <div class="d-flex justify-content-around">

    <div>

      <% unless current_user == @user || Friendship.exists?(asker: current_user, receiver: @user, is_accepted: true) ||Friendship.exists?(asker: @user, receiver: current_user, is_accepted: true) %>
        <% friendship_request = Friendship.find_by(asker: current_user, receiver: @user, is_accepted: false) %>
        <% friendship_accepted = Friendship.find_by(asker: current_user, receiver: @user, is_accepted: true) %>
        <% if friendship_request %>
          <%= "Friendship request sent" %>
        <% elsif friendship_accepted %>
          <%= "#{friendship_accepted.receiver.nickname} is already your friend" %>
        <% else %>
          <%= button_to "Follow", add_friend_user_path(@user),class:'button-one', method: :post %>
        <% end %>
      <% end %>

    <div class="requests-notifications">
      <% if @pending_friendships.any? && @user == current_user %>
        <% requests = @pending_friendships.count %>
        <% f = @pending_friendships.first %>
          <div class="text-center">

            <%= requests > 1 ?  "You Have #{requests} New Friends!" : "You Have a New Friend!" %>

            <div class="request-container-card">
              <div class="button-container">

                <span class="nickname"><%= f.asker.nickname %></span> Wants to be your friend

                <div class="two-buttons">
                  <%= button_to "Accept", accept_friendship_user_path(f), method: :patch, class: 'button-accept' %>
                  <%= button_to "Decline", decline_friendship_user_path(f), method: :delete, class: 'button-decline' %>
                </div>

              </div>
            </div>

          </div>

        <% end %>
      </div>

  </div>


    <% if Friendship.exists?(asker_id: current_user.id, receiver_id: @user.id, is_accepted: true) || Friendship.exists?(asker_id: @user.id, receiver_id: current_user.id, is_accepted: true) %>
      <%= link_to "message", chatroom_path(@chatroom), class: 'button-two'%>
    <% end %>

  </div>

  <div class="mt-4">

    <div class="m-3">
      <h3 class="home-categories-titles">My favorite universes</h3>
      <%= render 'shared/home_content' %>
    </div>

    <div class="m-3">
      <h3 class="home-categories-titles">Last reads</h3>
      <%= render 'shared/home_content' %>
    </div>

  </div>

</div>