config/routes.rb
Rails.application.routes.draw do
  get 'messages/create'
  devise_for :users
  root to: "pages#home"

  get "search", to: "universes#search"
  resources :universes, only: [:index, :show] do
    resources :bookmarks, only: [:create, :destroy]
  end

  resources :stories, only: [:show]

  resources :pages, only: [:show]

  resources :tags, only: [:show]

  resources :users, only: [:show] do
    resources :chatrooms, only: [:create]
    member do
      post :add_friend
      patch :accept_friendship
      delete :decline_friendship
      get :friends
      delete :delete_friendship
    end
  end

  resources :chatrooms, only: [:show] do
    resources :messages, only: [:create]
  end

  resources :avatars, only: %i[new create]
end

app/controllers/universes_controller.rb
class UniversesController < ApplicationController
  def show
    @universe = Universe.find(params[:id])
    authorize @universe
    @bookmark = Bookmark.new
    authorize @bookmark
    @story = @universe.stories
    authorize @story
  end

  def search
    @tags = Tag.all
    @colors = ["pink", "green", "yellow", "blue", "grey", "lightgrey", "darkblue", "purple", "white", "red"]
    @universes = Universe.all
    authorize @universes
    if params[:query].present?
      @universes = Universe.where("title ILIKE ?", "%#{params[:query]}%")
      @universes = policy_scope(@universes)
    else
      @universes = policy_scope(Universe)
    end
    respond_to do |format|
      format.html
      format.text { render partial: "universes/list", locals: { universes: @universes, colors: @colors }, formats: [:html]}
    end
  end
end

app/views/universes/_list.html.erb
<div data-search-universes-target="list">
  <% if params[:query].present? %>
    <div class="row justify-content-evenly">
      <% @universes.each do |universe| %>
        <%= link_to universe_path(universe), class: "universe-card col-6 my-3" do %>
          <div class="card-category">
            <%= image_tag universe.thumb_url, width: "50%" %>
          </div>
        <% end %>
      <% end %>
    </div>
  <% else %>
    <div class="row justify-content-evenly">
      <% @tags.each_with_index do |tag, index| %>
          <div class="card-category search-bg-<%= colors[index] %>", style="color: black">
            <%= link_to tag_path(tag) do %>
            <div>
              <div class="size-icon">
                <%= image_tag tag.thumb_url, width: "50%" %>
              </div>
              <div>
                <h3 class="font-card"><%= tag.name %></h3>
              </div>
            <% end %>
            </div>
          </div>
      <% end %>
    </div>
  <%end%>
</div>

app/views/universes/search.html.erb
<div data-controller="search-universes" class="container ">

  <%= form_with url: search_path, method: :get, html: {class:
    "my-3", data: {search_universes_target: "form"}} do |f| %>
    <%= f.text_field :query,
                     class: "form-control universe_search text-center",
                     placeholder: "What are you looking for?",
                     value: params[:query],
                     data: {search_universes_target: "input",
                     action: "keyup->search-universes#update"
                     } %>
  <% end %>

  <%= render 'universes/list', universes: @universes, colors: @colors %>

</div>

app/views/universes/show.html.erb
<div data-controller="expander-stories" >

  <div class="t-universe-container container">

    <div class="t-main-card">


    <%= image_tag @universe.thumb_url, class: "universe-image" %>

      <div class="universe-title-description">
        <h3><%= @universe.title %></h3>
        <h6><%= @universe.callout %></h6>
      </div>

    </div>

    <div class="card-description" data-expander-stories-target="ucontent">
        <p><%= @universe.content %></p>
    </div>

    <div class="icon universe-icons">

      <div>

        <% if user_signed_in? %>

          <% if @universe.bookmarks.any? { |book| book[:user_id] == current_user.id} %>
            <% @bookmark = @universe.bookmarks.find { |bookmark| bookmark[:user_id] == current_user.id } %>
            <%= link_to universe_bookmark_path(@universe, @bookmark) ,data: {turbo_method: :delete} do %>
              <i class="fas fa-heart" aria-hidden="true"></i>
            <% end %>
          <% else %>
            <%= simple_form_for [@universe, @bookmark] do |f|%>
              <%= button_tag type: 'submit', class: "button postfix" do %>
                <i class="far fa-heart" aria-hidden="true"></i>
              <% end %>
            <% end %>
          <% end %>

        <% end %>

      </div>

      <i class="fa-solid fa-share"></i>

    </div>

  </div>





  <% @universe.stories.each do |story| %>
    <div class="t-card-story container" data-action="click->expander-stories#expand" data-expander-stories-target="story">

      <div>
        <%= image_tag story.thumb_url, class:"story-img" %>
      </div>

      <div class="t-card-story-content">

        <div class="t-card-story-content-extra">
          <h3><%= story.title %></h3>
          <p><%= story.callout %></p>
          <span><%= story.reading_time %> minutes</span>
        </div>

        <div  class="story-hyde" data-expander-stories-target="scontent">
          <p><%= story.content %></p>
        </div>

        <div class="t-card-story-details">
          <span class="sticker-tag">Mistery</span>

          <%=link_to "read", story_path(story), class: "button-four-small"%>
        </div>


      </div>

    </div>
  <% end %>

</div>